import type { PortalBillingCategory } from "../repositories/adminFinanceRepository.js";
import { CLINICAL_RATE, DIDACTIC_RATE } from "../services/billingMath.js";

/** MAHM 2025–26 Catalog (March 31, 2026) fee SKUs exposed in the student portal store. */
export type StoreFeeSku = {
  code: string;
  nameEn: string;
  nameZh: string;
  descriptionEn: string;
  descriptionZh: string;
  unitPriceUsd: number;
  category: PortalBillingCategory;
  /** When true, checkout accepts quantity > 1 (e.g. transfer evaluation per course). */
  allowQuantity: boolean;
  maxQuantity: number;
  catalogRef: string;
};

export const STORE_FEE_CATALOG: StoreFeeSku[] = [
  {
    code: "graduation_evaluation",
    nameEn: "Graduation Evaluation / Commencement",
    nameZh: "毕业评估 / 毕业典礼",
    descriptionEn: "Graduation evaluation and commencement fee (MAHM Catalog).",
    descriptionZh: "毕业评估与毕业典礼费用（学生手册价目）。",
    unitPriceUsd: 350,
    category: "fees",
    allowQuantity: false,
    maxQuantity: 1,
    catalogRef: "Tuition and Fees — Graduation Evaluation $350",
  },
  {
    code: "institutional_exam",
    nameEn: "Institutional Exam Registration",
    nameZh: "机构考试注册费",
    descriptionEn:
      "$50 per exam registration. Catalog credit rules (pass credit / first-try waiver) apply after payment — contact the registrar.",
    descriptionZh: "每场考试注册 $50。通过返还等手册规则在付款后由注册处处理。",
    unitPriceUsd: 50,
    category: "exam",
    allowQuantity: false,
    maxQuantity: 1,
    catalogRef: "Institutional Exam Fees — $50 each",
  },
  {
    code: "makeup_exam",
    nameEn: "Make-Up Exam Fee",
    nameZh: "补考费",
    descriptionEn: "Make-up exam fee after approved make-up test form ($50).",
    descriptionZh: "经批准的补考申请后收取（$50）。",
    unitPriceUsd: 50,
    category: "exam",
    allowQuantity: false,
    maxQuantity: 1,
    catalogRef: "Institutional Exam and Make-Up Exam Fee — $50",
  },
  {
    code: "independent_study",
    nameEn: "Independent Study",
    nameZh: "独立研究课程",
    descriptionEn: "Independent study course fee ($300 per course).",
    descriptionZh: "独立研究课程费用（每门 $300）。",
    unitPriceUsd: 300,
    category: "tuition",
    allowQuantity: false,
    maxQuantity: 1,
    catalogRef: "Independent Study — $300 per course",
  },
  {
    code: "transfer_evaluation",
    nameEn: "Transfer Credit Evaluation",
    nameZh: "转学分评估费",
    descriptionEn: "Additional transfer evaluation after admission ($100 per course). Initial evaluation is free.",
    descriptionZh: "入学后额外转学分评估（每门 $100）。首次评估免费。",
    unitPriceUsd: 100,
    category: "fees",
    allowQuantity: true,
    maxQuantity: 10,
    catalogRef: "Additional Subsequent Transfer Fee — $100 per course",
  },
  {
    code: "application_fee",
    nameEn: "Master's Application Fee",
    nameZh: "硕士申请费",
    descriptionEn: "Non-refundable application fee for U.S. citizens/residents ($100).",
    descriptionZh: "美国公民/居民申请费（不可退，$100）。",
    unitPriceUsd: 100,
    category: "other",
    allowQuantity: false,
    maxQuantity: 1,
    catalogRef: "Master's Application Fee — $100",
  },
  {
    code: "i20_application",
    nameEn: "I-20 Student Application",
    nameZh: "I-20 学生申请费",
    descriptionEn: "Non-refundable I-20 application fee for international students ($150).",
    descriptionZh: "国际学生 I-20 申请费（不可退，$150）。",
    unitPriceUsd: 150,
    category: "other",
    allowQuantity: false,
    maxQuantity: 1,
    catalogRef: "I-20 Student Application — $150",
  },
  {
    code: "non_matriculating_application",
    nameEn: "Non-Matriculating Application",
    nameZh: "非学位生申请费",
    descriptionEn: "Non-refundable non-matriculating student application fee ($150).",
    descriptionZh: "非学位生申请费（不可退，$150）。",
    unitPriceUsd: 150,
    category: "other",
    allowQuantity: false,
    maxQuantity: 1,
    catalogRef: "Non-Matriculating Student Application — $150",
  },
  {
    code: "official_transcript",
    nameEn: "Official Transcript",
    nameZh: "官方成绩单",
    descriptionEn: "Official transcript request ($15 each).",
    descriptionZh: "官方成绩单（每份 $15）。",
    unitPriceUsd: 15,
    category: "fees",
    allowQuantity: true,
    maxQuantity: 10,
    catalogRef: "Official Transcript — $15",
  },
  {
    code: "certificate_attendance",
    nameEn: "Certificate of Attendance",
    nameZh: "在学证明",
    descriptionEn: "Certificate of attendance ($10).",
    descriptionZh: "在学证明（$10）。",
    unitPriceUsd: 10,
    category: "fees",
    allowQuantity: true,
    maxQuantity: 5,
    catalogRef: "Certificate of Attendance — $10",
  },
  {
    code: "certificate_graduation",
    nameEn: "Certificate of Graduation",
    nameZh: "毕业证明",
    descriptionEn: "Certificate of graduation ($10).",
    descriptionZh: "毕业证明（$10）。",
    unitPriceUsd: 10,
    category: "fees",
    allowQuantity: true,
    maxQuantity: 5,
    catalogRef: "Certificate of Graduation — $10",
  },
  {
    code: "diploma_copy",
    nameEn: "Additional Copy of Diploma",
    nameZh: "额外文凭副本",
    descriptionEn: "Additional diploma copy ($100).",
    descriptionZh: "额外文凭副本（$100）。",
    unitPriceUsd: 100,
    category: "fees",
    allowQuantity: true,
    maxQuantity: 3,
    catalogRef: "Additional Copy of Diploma — $100",
  },
  {
    code: "id_card",
    nameEn: "Student / Intern ID Card",
    nameZh: "学生/实习证",
    descriptionEn: "Student or intern ID card ($20).",
    descriptionZh: "学生或实习证（$20）。",
    unitPriceUsd: 20,
    category: "fees",
    allowQuantity: true,
    maxQuantity: 3,
    catalogRef: "Student/Intern ID card — $20",
  },
  {
    code: "abroad_mailing",
    nameEn: "Abroad Mailing Service",
    nameZh: "海外邮寄服务",
    descriptionEn: "Abroad mailing service — letter ($120).",
    descriptionZh: "海外邮寄服务（信函 $120）。",
    unitPriceUsd: 120,
    category: "fees",
    allowQuantity: false,
    maxQuantity: 1,
    catalogRef: "Abroad Mailing Service — $120",
  },
  {
    code: "lab_coat",
    nameEn: "Lab Coat",
    nameZh: "实验袍",
    descriptionEn: "Lab coat ($50).",
    descriptionZh: "实验袍（$50）。",
    unitPriceUsd: 50,
    category: "fees",
    allowQuantity: true,
    maxQuantity: 2,
    catalogRef: "Lab Coat — $50",
  },
  {
    code: "herbal_education_box",
    nameEn: "Herbal Education Box I–IV",
    nameZh: "中药教育盒 I–IV",
    descriptionEn: "Herbal education box set ($200).",
    descriptionZh: "中药教育盒套装（$200）。",
    unitPriceUsd: 200,
    category: "fees",
    allowQuantity: true,
    maxQuantity: 2,
    catalogRef: "Herbal Education Box I–IV — $200",
  },
  {
    code: "i20_reissue",
    nameEn: "I-20 Re-Issue",
    nameZh: "I-20 重新签发",
    descriptionEn: "I-20 re-issue fee ($100).",
    descriptionZh: "I-20 重新签发费（$100）。",
    unitPriceUsd: 100,
    category: "fees",
    allowQuantity: false,
    maxQuantity: 1,
    catalogRef: "I-20 Re-Issue Fee — $100",
  },
  {
    code: "late_registration",
    nameEn: "Late Registration Fee",
    nameZh: "延迟注册费",
    descriptionEn: "Late registration fee ($30).",
    descriptionZh: "延迟注册费（$30）。",
    unitPriceUsd: 30,
    category: "fees",
    allowQuantity: false,
    maxQuantity: 1,
    catalogRef: "Late Registration Fee — $30",
  },
  {
    code: "add_drop_fee",
    nameEn: "Additional Add/Drop Fee",
    nameZh: "加退课手续费",
    descriptionEn: "Additional add/drop request fee ($20 per request).",
    descriptionZh: "额外加退课申请费（每次 $20）。",
    unitPriceUsd: 20,
    category: "fees",
    allowQuantity: true,
    maxQuantity: 10,
    catalogRef: "Additional Add/drop Fee — $20 per request",
  },
  {
    code: "credit_unit_topup",
    nameEn: "Didactic Credit Unit Top-Up",
    nameZh: "学分单价补差价",
    descriptionEn: `Pay a tuition balance adjustment at the catalog didactic rate ($${DIDACTIC_RATE} per credit unit). Set quantity to the number of units owed.`,
    descriptionZh: `按手册理论课学分单价（$${DIDACTIC_RATE}/学分）补缴学费差额。数量请填写需补的学分数。`,
    unitPriceUsd: DIDACTIC_RATE,
    category: "tuition",
    allowQuantity: true,
    maxQuantity: 30,
    catalogRef: `Tuition — $${DIDACTIC_RATE} per didactic credit unit`,
  },
  {
    code: "clinical_hour_topup",
    nameEn: "Clinical Clock Hour Top-Up",
    nameZh: "诊所学分单价补差价",
    descriptionEn: `Pay a clinical training balance adjustment at the catalog rate ($${CLINICAL_RATE} per clock hour). Set quantity to the number of clinic hours owed.`,
    descriptionZh: `按手册诊所临床时数单价（$${CLINICAL_RATE}/小时）补缴差额。数量请填写需补的临床时数。`,
    unitPriceUsd: CLINICAL_RATE,
    category: "clinical",
    allowQuantity: true,
    maxQuantity: 200,
    catalogRef: `Clinical training — $${CLINICAL_RATE} per clock hour`,
  },
];

const catalogByCode = new Map(STORE_FEE_CATALOG.map((s) => [s.code, s]));

export function getStoreFeeSku(code: string): StoreFeeSku | null {
  return catalogByCode.get(code.trim()) ?? null;
}

export function listStoreFeeCatalog(): StoreFeeSku[] {
  return [...STORE_FEE_CATALOG];
}
